'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>('id');

    useEffect(() => {
        // Load language from localStorage
        const savedLanguage = localStorage.getItem('language') as Language;
        if (savedLanguage) {
            setLanguageState(savedLanguage);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

// Translations
const translations: Record<Language, Record<string, string>> = {
    id: {
        // Navigation
        'nav.home': 'Beranda',
        'nav.events': 'Event',
        'nav.calendar': 'Kalender',
        'nav.discover': 'Jelajahi',
        'nav.dashboard': 'Dashboard',
        'nav.login': 'Masuk',
        'nav.editProfile': 'Edit Profil',
        'nav.createEvent': 'Buat Event',
        'nav.signOut': 'Keluar',

        // Home
        'home.title': 'Event Terbaru',
        'home.subtitle': 'Jelajahi event-event menarik yang tersedia',
        'home.upcoming': 'Yang Akan Datang',
        'home.past': 'Masa Lampau',
        'home.loading': 'Memuat event...',
        'home.noUpcoming': 'Belum ada event yang akan datang',
        'home.noUpcomingDesc': 'Event baru akan segera hadir',
        'home.noPast': 'Belum ada event sebelumnya',
        'home.noPastDesc': 'Belum ada event yang telah berlalu',
        'home.viewAll': 'Lihat Semua Event',
        'home.free': 'GRATIS',
        'home.viewDetails': 'Lihat Detail →',

        // Event Detail
        'event.featured': '🌟 Unggulan',
        'event.in': 'di',
        'event.location': 'Lokasi',
        'event.aboutEvent': 'Tentang Event',
        'event.speakers': 'Pembicara',
        'event.registration': 'Pendaftaran',
        'event.registrationFee': 'Biaya Pendaftaran',
        'event.freeEvent': 'EVENT GRATIS',
        'event.completeProfile': 'Lengkapi Profil Anda',
        'event.completeProfileDesc': 'Anda harus melengkapi profil terlebih dahulu sebelum dapat mendaftar event. Pastikan Nama Lengkap dan Nomor Telepon sudah terisi.',
        'event.completeProfileNow': 'Lengkapi Profil Sekarang',
        'event.selectOption': 'Pilih...',
        'event.fileUploadSuccess': 'File berhasil diunggah',
        'event.uploading': 'Mengunggah...',
        'event.clickToUpload': 'Klik untuk unggah',
        'event.orDragDrop': 'atau seret dan lepas',
        'event.fileFormat': 'PNG, JPG, PDF (MAKS. 5MB)',
        'event.requestToJoin': 'Daftar Sekarang',
        'event.completeProfileFirst': 'Lengkapi Profil Dulu',
        'event.loginToRegister': 'Silakan masuk untuk mendaftar event ini',
        'event.alreadyRegistered': 'Sudah Terdaftar!',
        'event.registrationSuccess': 'Anda telah berhasil mendaftar untuk event ini. Kami akan mengirimkan email konfirmasi.',
        'event.registrationSuccessToast': 'Pendaftaran berhasil!',
        'event.registrationError': 'Gagal mendaftar event',
        'event.notFound': 'Event tidak ditemukan',
        'event.backToEvents': 'Kembali ke daftar event',

        // Discover
        'discover.title': 'Jelajahi Event',
        'discover.subtitle': 'Temukan event populer di sekitar Anda, jelajahi berdasarkan kategori, atau lihat kalender komunitas.',
        'discover.browseByCategory': 'Jelajahi Berdasarkan Kategori',
        'discover.events': 'event',

        // Events List
        'events.title': 'Temukan Event Menarik',
        'events.subtitle': 'Jelajahi berbagai event menarik dan daftar sekarang juga',
        'events.filterBy': 'Filtering by:',
        'events.search': 'Cari event...',
        'events.allCategories': 'Semua Kategori',
        'events.noEvents': 'Tidak ada event',
        'events.noEventsDesc': 'Belum ada event yang tersedia saat ini.',
        'event.capacity': 'Kapasitas Event',
        'event.registrationClosed': 'Pendaftaran Ditutup',
        'event.capacityReached': 'Kapasitas Penuh',
        'event.cancel': 'Batalkan Pendaftaran',
        'event.registrationForm': 'Formulir Pendaftaran',
        'events.eventFound': 'event ditemukan',
        'events.eventsFound': 'event ditemukan',

        // Common
        'common.loading': 'Memuat...',
        'common.error': 'Terjadi kesalahan',
        'common.success': 'Berhasil',
        'common.cancel': 'Batal',
        'common.save': 'Simpan',
        'common.delete': 'Hapus',
        'common.edit': 'Edit',
        'common.back': 'Kembali',
        'common.viewDetails': 'Lihat Detail',
        'common.register': 'Daftar',
        'common.submit': 'Kirim',
        'common.close': 'Tutup',
        'common.gridView': 'Tampilan Grid',
        'common.grid': 'Grid',
        'common.timelineView': 'Tampilan Timeline',
        'common.timeline': 'Timeline',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.myEvents': 'Event Saya',
        'dashboard.createEvent': 'Buat Event Baru',
        'dashboard.editEvent': 'Edit Event',
        'dashboard.deleteEvent': 'Hapus Event',
        'dashboard.registrations': 'Pendaftaran',
        'dashboard.noEvents': 'Anda belum membuat event',
        'dashboard.createFirst': 'Buat event pertama Anda sekarang',
        'dashboard.published': 'Published',
        'dashboard.draft': 'Draft',
        'dashboard.viewRegistrations': 'Lihat Pendaftaran',
        'dashboard.registeredUsers': 'peserta terdaftar',

        // Calendar
        'calendar.title': 'Kalender Event',
        'calendar.subtitle': 'Lihat semua event dalam tampilan kalender',
        'calendar.today': 'Hari Ini',
        'calendar.tomorrow': 'Besok',
        'calendar.month': 'Bulan',
        'calendar.week': 'Minggu',
        'calendar.day': 'Hari',
        'calendar.noEventsThisDay': 'Tidak ada event pada hari ini',

        // Profile
        'profile.title': 'Edit Profile',
        'profile.subtitle': 'Kelola informasi profil Anda',
        'profile.fullName': 'Nama Lengkap',
        'profile.email': 'Email',
        'profile.phone': 'Nomor Telepon',
        'profile.bio': 'Bio',
        'profile.photo': 'Foto Profil',
        'profile.uploadPhoto': 'Upload Foto',
        'profile.changePhoto': 'Ganti Foto',
        'profile.saving': 'Menyimpan...',
        'profile.saveChanges': 'Simpan Perubahan',
        'profile.saved': 'Profil berhasil disimpan!',

        // Auth
        'auth.login': 'Masuk',
        'auth.loginTitle': 'Masuk ke Akun Anda',
        'auth.loginSubtitle': 'Selamat datang kembali!',
        'auth.loginWithGoogle': 'Masuk dengan Google',
        'auth.loggingIn': 'Masuk...',
        'auth.loginError': 'Gagal masuk. Silakan coba lagi.',
        'auth.register': 'Daftar',
        'auth.registerTitle': 'Buat Akun Baru',
        'auth.registerSubtitle': 'Bergabunglah dengan komunitas kami',
        'auth.email': 'Email',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Konfirmasi Password',
        'auth.fullName': 'Nama Lengkap',
        'auth.createAccount': 'Buat Akun',
        'auth.alreadyHaveAccount': 'Sudah punya akun?',
        'auth.dontHaveAccount': 'Belum punya akun?',
        'auth.registerNow': 'Daftar sekarang',
        'auth.orContinueWith': 'Atau lanjutkan dengan',
        'auth.emailRequired': 'Email harus diisi',
        'auth.passwordRequired': 'Password harus diisi',
        'auth.passwordMinLength': 'Password minimal 6 karakter',
        'auth.passwordMismatch': 'Password tidak cocok',
        'auth.nameRequired': 'Nama lengkap harus diisi',
        'auth.registerSuccess': 'Registrasi berhasil! Silakan cek email untuk verifikasi.',
        'auth.registerError': 'Gagal mendaftar. Silakan coba lagi.',
        'auth.invalidCredentials': 'Email atau password salah',
        'auth.emailAlreadyExists': 'Email sudah terdaftar',

        // Create/Edit Event
        'eventForm.createTitle': 'Buat Event Baru',
        'eventForm.editTitle': 'Edit Event',
        'eventForm.basicInfo': 'Informasi Dasar',
        'eventForm.eventTitle': 'Judul Event',
        'eventForm.description': 'Deskripsi',
        'eventForm.category': 'Kategori',
        'eventForm.selectCategory': 'Pilih Kategori',
        'eventForm.dateTime': 'Tanggal & Waktu',
        'eventForm.startDate': 'Tanggal Mulai',
        'eventForm.endDate': 'Tanggal Selesai',
        'eventForm.locationInfo': 'Informasi Lokasi',
        'eventForm.location': 'Lokasi',
        'eventForm.registrationInfo': 'Informasi Pendaftaran',
        'eventForm.registrationFee': 'Biaya Pendaftaran',
        'eventForm.maxParticipants': 'Maksimal Peserta',
        'eventForm.unlimited': 'Unlimited',
        'eventForm.imageUpload': 'Upload Gambar',
        'eventForm.uploadImage': 'Upload Gambar Event',
        'eventForm.changeImage': 'Ganti Gambar',
        'eventForm.speakers': 'Speakers',
        'eventForm.addSpeaker': 'Tambah Speaker',
        'eventForm.speakerName': 'Nama Speaker',
        'eventForm.speakerTitle': 'Jabatan',
        'eventForm.speakerBio': 'Bio Speaker',
        'eventForm.speakerPhoto': 'Foto Speaker',
        'eventForm.removeSpeaker': 'Hapus Speaker',
        'eventForm.customFields': 'Form Pendaftaran Kustom',
        'eventForm.addField': 'Tambah Field',
        'eventForm.fieldLabel': 'Label Field',
        'eventForm.fieldType': 'Tipe Field',
        'eventForm.required': 'Wajib Diisi',
        'eventForm.status': 'Status',
        'eventForm.draft': 'Draft',
        'eventForm.published': 'Published',
        'eventForm.creating': 'Membuat Event...',
        'eventForm.updating': 'Mengupdate Event...',
        'eventForm.create': 'Buat Event',
        'eventForm.update': 'Update Event',
        'eventForm.created': 'Event berhasil dibuat!',
        'eventForm.updated': 'Event berhasil diupdate!',
        'eventForm.createSubtitle': 'Bagikan event Anda dengan dunia. Isi detail di bawah untuk memulai.',
        'eventForm.editSubtitle': 'Perbarui informasi event Anda.',
        'eventForm.tabBasic': 'Info Dasar',
        'eventForm.tabSpeakers': 'Pembicara',
        'eventForm.tabRegistration': 'Form Pendaftaran',
        'eventForm.tabImages': 'Form Gambar Kustom',
        'eventForm.eventDetails': 'Detail Event',
        'eventForm.eventDetailsDesc': 'Informasi dasar tentang event Anda.',
        'eventForm.coverImage': 'Gambar Cover Event',
        'eventForm.imageRatioWarning': 'Rekomendasi rasio gambar 4:5. Gambar akan terpotong jika rasio tidak sesuai.',
        'eventForm.clickUpload': 'Klik untuk upload atau seret dan lepas',
        'eventForm.imageFormat': 'PNG, JPG atau WEBP (MAKS. 5MB)',
        'eventForm.titlePlaceholder': 'mis., Konferensi Teknologi Tahunan 2024',
        'eventForm.descriptionPlaceholder': 'Deskripsikan event Anda menggunakan markdown...',
        'eventForm.markdownSupport': 'Mendukung format Markdown',
        'eventForm.startDateTime': 'Tanggal & Waktu Mulai',
        'eventForm.endDateTime': 'Tanggal & Waktu Selesai',
        'eventForm.locationPlaceholder': 'mis., Zoom Meeting atau Alamat Fisik',
        'eventForm.selectCategoryPlaceholder': 'Pilih kategori...',
        'eventForm.capacityPlaceholder': 'Maksimal peserta',
        'eventForm.registrationFeeIDR': 'Biaya Pendaftaran (IDR)',
        'eventForm.feePlaceholder': '0 (Event gratis)',
        'eventForm.feeHelper': 'Biarkan 0 untuk event gratis. Jika Anda menetapkan biaya, pastikan untuk menambahkan field upload bukti pembayaran di bawah.',
        'eventForm.draftDesc': 'Simpan untuk nanti, tidak terlihat publik',
        'eventForm.publishedDesc': 'Terlihat semua orang segera',
        'eventForm.registrationFormTitle': 'Form Pendaftaran',
        'eventForm.registrationFormDesc': 'Sesuaikan informasi apa yang Anda butuhkan dari peserta.',
        'eventForm.noCustomFields': 'Tidak Ada Field Kustom',
        'eventForm.noCustomFieldsDesc': 'Mulai dengan menambahkan field untuk mengumpulkan informasi spesifik dari peserta Anda.',
        'eventForm.addFirstField': 'Tambahkan field pertama Anda',
        'eventForm.fieldName': 'Nama Field',
        'eventForm.fieldNamePlaceholder': 'mis., Nomor Telepon',
        'eventForm.type': 'Tipe',
        'eventForm.typeText': 'Teks',
        'eventForm.typeEmail': 'Email',
        'eventForm.typeNumber': 'Angka',
        'eventForm.typeTextarea': 'Textarea',
        'eventForm.typeSelect': 'Pilihan',
        'eventForm.typeFile': 'Upload File',
        'eventForm.speakersTitle': 'Pembicara',
        'eventForm.speakersDesc': 'Siapa yang akan presentasi di event Anda?',
        'eventForm.noSpeakers': 'Belum Ada Pembicara',
        'eventForm.noSpeakersDesc': 'Sorot para ahli dan tamu yang akan hadir.',
        'eventForm.addFirstSpeaker': 'Tambahkan pembicara pertama Anda',
        'eventForm.speakerNumber': 'Pembicara',
        'eventForm.customImagesTitle': 'Gambar Kustom untuk Form Pendaftaran',
        'eventForm.customImagesDesc': 'Tambahkan gambar kustom yang akan ditampilkan dalam form pendaftaran.',
        'eventForm.addImage': 'Tambah Gambar',
        'eventForm.noCustomImages': 'Belum Ada Gambar Kustom',
        'eventForm.noCustomImagesDesc': 'Tambahkan gambar untuk memperkaya form pendaftaran Anda.',
        'eventForm.addFirstImage': 'Tambahkan gambar pertama Anda',
        'eventForm.imageTitle': 'Judul Gambar',
        'eventForm.imageDescription': 'Deskripsi Gambar',
        'eventForm.uploadingImage': 'Mengompresi dan mengupload gambar...',
        'eventForm.imageUploaded': 'Gambar berhasil diupload!',
        'eventForm.imageUploadFailed': 'Gagal upload gambar',
        'eventForm.pleaseLogin': 'Silakan login terlebih dahulu',
        'eventForm.loginError': 'Terjadi kesalahan saat verifikasi login',
        'eventForm.fillRequired': 'Mohon lengkapi semua field yang wajib diisi',
        'eventForm.createError': 'Gagal membuat event',
        'eventForm.updateError': 'Gagal mengupdate event',
        'eventForm.paymentProofAdded': 'Form upload bukti pembayaran ditambahkan otomatis',

        // Registrations
        'registrations.title': 'Pendaftaran Event',
        'registrations.subtitle': 'Kelola peserta yang terdaftar',
        'registrations.total': 'Total Pendaftaran',
        'registrations.export': 'Export Data',
        'registrations.name': 'Nama',
        'registrations.email': 'Email',
        'registrations.phone': 'Telepon',
        'registrations.registeredAt': 'Tanggal Daftar',
        'registrations.status': 'Status',
        'registrations.approved': 'Disetujui',
        'registrations.pending': 'Pending',
        'registrations.rejected': 'Ditolak',
        'registrations.noRegistrations': 'Belum ada pendaftaran',

        // About
        'about.title': 'Tentang Ngevent',
        'about.appTitle': 'Tentang Aplikasi Ngevent',
        'about.appDesc': 'Ngevent membantu Anda membuat dan mengelola acara online dengan mudah. Buat acara, kelola peserta, dan lihat informasi dasar acara melalui dashboard yang sederhana.',
        'about.featuresTitle': 'Fitur Utama',
        'about.featuresDesc': 'Beberapa fitur utama Ngevent:',
        'about.feature1': 'Buat dan kelola acara online',
        'about.feature2': 'Registrasi peserta',
        'about.feature3': 'Dashboard sederhana untuk melihat data acara',
        'about.feature4': 'Antarmuka responsif untuk perangkat mobile',
        'about.feature5': 'Dukungan beberapa bahasa',
        'about.devTitle': 'Informasi Pengembang',
        'about.devDesc': 'Ngevent dibuat dan dipelihara oleh komunitas DevOps Jogja. Proyek ini menggunakan teknologi modern seperti Next.js, TypeScript, Tailwind CSS, dan Supabase.',
        'about.community': 'Komunitas:',
        'about.tech': 'Teknologi:',
        'about.supportTitle': 'Dukungan dan Kontak',
        'about.supportDesc': 'Kami menjaga layanan dan keamanan platform. Jika Anda membutuhkan bantuan, silakan hubungi komunitas DevOps Jogja.',
        'about.support1': 'Monitoring dan pemeliharaan rutin',
        'about.support2': 'Backup dan update keamanan berkala',
        'about.support3': 'Dukungan teknis dari komunitas',
        'about.contact': 'Kontak:',
        'about.telegram': 'Telegram:',

        // Terms
        'terms.title': 'Syarat dan Ketentuan',
        'terms.lastUpdated': 'Terakhir diperbarui:',
        'terms.section1.title': '1. Penerimaan Syarat',
        'terms.section1.content': 'Dengan mengakses dan menggunakan platform Ngevent, Anda menyetujui untuk terikat oleh Syarat dan Ketentuan ini. Jika Anda tidak setuju dengan syarat-syarat ini, mohon untuk tidak menggunakan platform kami.',
        'terms.section2.title': '2. Deskripsi Layanan',
        'terms.section2.content': 'Ngevent adalah platform manajemen event online yang memudahkan penyelenggara dan peserta dalam mengelola dan berpartisipasi dalam berbagai acara. Layanan kami mencakup pembuatan event, pendaftaran peserta, manajemen pembayaran, dan komunikasi terkait event.',
        'terms.section3.title': '3. Akun Pengguna',
        'terms.section3.content': 'Untuk menggunakan layanan kami, Anda harus membuat akun dengan memberikan informasi yang akurat dan lengkap. Anda bertanggung jawab untuk:',
        'terms.section3.list1': 'Menjaga kerahasiaan kata sandi Anda',
        'terms.section3.list2': 'Menggunakan akun Anda hanya untuk tujuan yang sah',
        'terms.section3.list3': 'Memberikan informasi yang benar dan terkini',
        'terms.section3.list4': 'Melaporkan aktivitas yang mencurigakan pada akun Anda',
        'terms.section4.title': '4. Penggunaan yang Dilarang',
        'terms.section4.content': 'Anda dilarang menggunakan platform kami untuk:',
        'terms.section4.list1': 'Melanggar hukum atau peraturan yang berlaku',
        'terms.section4.list2': 'Mengirim konten yang tidak pantas, menghina, atau ilegal',
        'terms.section4.list3': 'Mengganggu operasi platform atau server kami',
        'terms.section4.list4': 'Mencoba mengakses area yang tidak diizinkan',
        'terms.section4.list5': 'Menyalin atau mendistribusikan konten tanpa izin',
        'terms.section5.title': '5. Konten Pengguna',
        'terms.section5.content': 'Anda bertanggung jawab atas konten yang Anda unggah atau bagikan di platform kami. Kami berhak menghapus konten yang melanggar syarat dan ketentuan ini tanpa pemberitahuan sebelumnya.',
        'terms.section6.title': '6. Pembayaran dan Pengembalian Dana',
        'terms.section6.content': 'Untuk event berbayar:',
        'terms.section6.list1': 'Pembayaran dilakukan melalui gateway pembayaran yang tersedia',
        'terms.section6.list2': 'Pengembalian dana hanya dilakukan sesuai kebijakan penyelenggara event',
        'terms.section6.list3': 'Kami tidak bertanggung jawab atas perselisihan pembayaran dengan penyelenggara',
        'terms.section7.title': '7. Privasi',
        'terms.section7.content': 'Kami menghormati privasi Anda. Informasi pribadi yang dikumpulkan digunakan hanya untuk keperluan layanan dan sesuai dengan Kebijakan Privasi kami.',
        'terms.section8.title': '8. Penolakan Jaminan',
        'terms.section8.content': 'Platform kami disediakan "sebagaimana adanya" tanpa jaminan apapun. Kami tidak bertanggung jawab atas kerugian yang timbul dari penggunaan platform ini.',
        'terms.section9.title': '9. Batasan Tanggung Jawab',
        'terms.section9.content': 'Kami tidak bertanggung jawab atas kerugian langsung, tidak langsung, insidental, atau konsekuensial yang timbul dari penggunaan platform kami.',
        'terms.section10.title': '10. Perubahan Syarat',
        'terms.section10.content': 'Kami berhak mengubah syarat dan ketentuan ini kapan saja. Perubahan akan diberitahukan melalui platform kami.',
        'terms.section11.title': '11. Hukum yang Berlaku',
        'terms.section11.content': 'Syarat dan ketentuan ini diatur oleh hukum Republik Indonesia.',
        'terms.section12.title': '12. Kontak Kami',
        'terms.section12.content': 'Jika Anda memiliki pertanyaan tentang syarat dan ketentuan ini, silakan hubungi kami melalui email atau fitur dukungan di platform.',
        'terms.backToLogin': 'Kembali ke Login',
        'terms.backToRegister': 'Kembali ke Daftar',

        // Calendar
        'calendar.days.sun': 'Min',
        'calendar.days.mon': 'Sen',
        'calendar.days.tue': 'Sel',
        'calendar.days.wed': 'Rab',
        'calendar.days.thu': 'Kam',
        'calendar.days.fri': 'Jum',
        'calendar.days.sat': 'Sab',

        // Dashboard
        'dashboard.loginRequired': 'Silakan login terlebih dahulu untuk mengakses dashboard',
        'dashboard.roleUpdated': 'Role berhasil diupdate!',
        'dashboard.eventDeleted': 'Event berhasil dihapus',
        'dashboard.deleteFailed': 'Gagal menghapus event',
        'dashboard.greeting.morning': 'Selamat Pagi',
        'dashboard.greeting.afternoon': 'Selamat Siang',
        'dashboard.greeting.evening': 'Selamat Malam',
        'dashboard.header.subtitle': 'Berikut adalah aktivitas event Anda hari ini.',
        'dashboard.stats.totalEvents': 'Total Event',
        'dashboard.stats.eventsJoined': 'Event Diikuti',
        'dashboard.stats.eventsCreated': 'Event Dibuat',
        'dashboard.stats.allTime': 'Sepanjang Waktu',
        'dashboard.stats.active': 'Aktif',
        'dashboard.stats.publishedEvents': 'Event Published',
        'dashboard.stats.upcomingEvents': 'Event Akan Datang',
        'dashboard.stats.thisMonth': 'Bulan Ini',
        'dashboard.stats.newActivity': 'Aktivitas Baru',
        'dashboard.roleSwitcher.title': 'Tampilan Dashboard',
        'dashboard.roleSwitcher.subtitle': 'Beralih antara mengelola event dan mengikuti event',
        'dashboard.role.participant': 'Peserta',
        'dashboard.role.organizer': 'Penyelenggara',
        'dashboard.organizer.noEvents': 'Belum ada event',
        'dashboard.organizer.noEventsDesc': 'Mulai perjalanan Anda dengan membuat event pertama. Hanya butuh beberapa menit!',
        'dashboard.participant.myRegistrations': 'Pendaftaran Saya',
        'dashboard.participant.noRegistrations': 'Belum ada pendaftaran',
        'dashboard.participant.noRegistrationsDesc': 'Jelajahi event kami dan temukan yang menarik bagi Anda!',
        'dashboard.participant.browseEvents': 'Jelajahi Event',
        'dashboard.eventCard.linkCopied': 'Link event disalin',
        'dashboard.eventCard.registered': 'Terdaftar:',
        'dashboard.status.confirmed': 'Terkonfirmasi',
        'dashboard.status.attended': 'Hadir',
        'dashboard.status.cancelled': 'Dibatalkan',
        'dashboard.deleteModal.title': 'Hapus Event?',
        'dashboard.deleteModal.confirm': 'Apakah Anda yakin ingin menghapus',
        'dashboard.deleteModal.warning': 'Tindakan ini tidak dapat dibatalkan.',
        'dashboard.deleteModal.deleteButton': 'Hapus Event',
        'dashboard.deleteModal.deleting': 'Menghapus...',

        // Auth
        'auth.emailVerified': 'Email berhasil diverifikasi. Silakan login.',
        'auth.invalidEmail': 'Email tidak valid',
        'auth.humanVerificationRequired': 'Verifikasi manusia diperlukan',
        'auth.verificationFailed': 'Verifikasi gagal',
        'auth.humanVerificationFailed': 'Verifikasi manusia gagal',
        'auth.loginSuccess': 'Login berhasil!',
        'auth.verificationRequired': 'Verifikasi diperlukan untuk melanjutkan.',
        'auth.redirectingGoogle': 'Mengarahkan ke Google...',
        'auth.agreeToTerms': 'Dengan masuk, Anda menyetujui',
        'auth.agreeToTermsRegister': 'Dengan mendaftar, Anda menyetujui',
        'auth.termsAndConditions': 'Syarat & Ketentuan',
        'auth.passwordMinLength8': 'Password minimal 8 karakter',
        'auth.passwordMustContainNumber': 'Password harus mengandung angka',
        'auth.passwordMustContainNumberHint': 'Mengandung angka (0-9)',
        'auth.registering': 'Mendaftar...',

        // Common
        'common.requestTimeout': 'Request Timeout',
        'common.loadFailed': 'Gagal Memuat Data',
        'common.serverTimeout': 'Server membutuhkan waktu terlalu lama. Silakan coba refresh halaman.',
        'common.loadError': 'Terjadi kesalahan saat memuat event. Silakan coba lagi.',
        'common.refreshPage': 'Refresh Halaman',
        'common.onlineEvent': 'Event Online',
        'common.online': 'Online',
        'common.clearFilters': 'Hapus Filter',
        'common.free': 'Gratis',
        'common.organizer': 'Penyelenggara',
        'common.by': 'Oleh',
        'widget.eventsComingUp': 'event akan datang',
        'widget.eventsOn': 'Event pada',
        'widget.inDays': 'dalam {days} hari',
    },
    en: {
        // Navigation
        'nav.home': 'Home',
        'nav.events': 'Events',
        'nav.calendar': 'Calendar',
        'nav.discover': 'Discover',
        'nav.dashboard': 'Dashboard',
        'nav.login': 'Login',
        'nav.editProfile': 'Edit Profile',
        'nav.createEvent': 'Create Event',
        'nav.signOut': 'Sign Out',

        // Home
        'home.title': 'Latest Events',
        'home.subtitle': 'Explore interesting events available',
        'home.upcoming': 'Upcoming',
        'home.past': 'Past',
        'home.loading': 'Loading events...',
        'home.noUpcoming': 'No upcoming events',
        'home.noUpcomingDesc': 'New events coming soon',
        'home.noPast': 'No past events',
        'home.noPastDesc': 'No past events yet',
        'home.viewAll': 'View All Events',
        'home.free': 'FREE',
        'home.viewDetails': 'View Details →',

        // Event Detail
        'event.featured': '🌟 Featured',
        'event.in': 'in',
        'event.location': 'Location',
        'event.aboutEvent': 'About the Event',
        'event.speakers': 'Speakers',
        'event.registration': 'Registration',
        'event.registrationFee': 'Registration Fee',
        'event.freeEvent': 'FREE EVENT',
        'event.completeProfile': 'Complete Your Profile',
        'event.completeProfileDesc': 'You must complete your profile before registering for events. Make sure your Full Name and Phone Number are filled in.',
        'event.completeProfileNow': 'Complete Profile Now',
        'event.selectOption': 'Select...',
        'event.fileUploadSuccess': 'File uploaded successfully',
        'event.uploading': 'Uploading...',
        'event.clickToUpload': 'Click to upload',
        'event.orDragDrop': 'or drag and drop',
        'event.fileFormat': 'PNG, JPG, PDF (MAX. 5MB)',
        'event.requestToJoin': 'Request to Join',
        'event.completeProfileFirst': 'Complete Profile First',
        'event.loginToRegister': 'Please login to register for this event',
        'event.alreadyRegistered': 'Already Registered!',
        'event.registrationSuccess': 'You have successfully registered for this event. We\'ll send you a confirmation email.',
        'event.registrationSuccessToast': 'Registration successful!',
        'event.registrationError': 'Failed to register for event',
        'event.notFound': 'Event not found',
        'event.backToEvents': 'Back to event list',
        'event.cancel': 'Cancel Registration',
        'event.registrationForm': 'Registration Form',

        // Discover
        'discover.title': 'Discover Events',
        'discover.subtitle': 'Explore popular events near you, browse by category, or check out some of the great community calendars.',
        'discover.browseByCategory': 'Browse by Category',
        'discover.events': 'Events',

        // Events List
        'events.title': 'Find Interesting Events',
        'events.subtitle': 'Explore various interesting events and register now',
        'events.filterBy': 'Filtering by:',
        'events.search': 'Search events...',
        'events.allCategories': 'All Categories',
        'events.noEvents': 'No events',
        'events.noEventsDesc': 'No events available at this time.',
        'event.capacity': 'Event Capacity',
        'event.registrationClosed': 'Registration Closed',
        'event.capacityReached': 'Capacity Reached',
        'events.eventFound': 'event found',
        'events.eventsFound': 'events found',

        // Common
        'common.loading': 'Loading...',
        'common.error': 'An error occurred',
        'common.success': 'Success',
        'common.cancel': 'Cancel',
        'common.save': 'Save',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.back': 'Back',
        'common.viewDetails': 'View Details',
        'common.register': 'Register',
        'common.submit': 'Submit',
        'common.close': 'Close',
        'common.gridView': 'Grid View',
        'common.grid': 'Grid',
        'common.timelineView': 'Timeline View',
        'common.timeline': 'Timeline',
        'common.requestTimeout': 'Request Timeout',
        'common.loadFailed': 'Failed to Load Data',
        'common.serverTimeout': 'Server took too long. Please try refreshing the page.',
        'common.loadError': 'An error occurred while loading events. Please try again.',
        'common.refreshPage': 'Refresh Page',
        'common.onlineEvent': 'Online Event',
        'common.online': 'Online',
        'common.clearFilters': 'Clear Filters',
        'common.free': 'Free',
        'common.organizer': 'Organizer',
        'common.by': 'By',
        'widget.eventsComingUp': 'events coming up',
        'widget.eventsOn': 'Events on',
        'widget.inDays': 'in {days} days',

        // Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.myEvents': 'My Events',
        'dashboard.createEvent': 'Create New Event',
        'dashboard.editEvent': 'Edit Event',
        'dashboard.deleteEvent': 'Delete Event',
        'dashboard.registrations': 'Registrations',
        'dashboard.noEvents': 'You haven\'t created any events',
        'dashboard.createFirst': 'Create your first event now',
        'dashboard.published': 'Published',
        'dashboard.draft': 'Draft',
        'dashboard.viewRegistrations': 'View Registrations',
        'dashboard.registeredUsers': 'registered participants',
        'dashboard.loginRequired': 'Please login first to access the dashboard',
        'dashboard.roleUpdated': 'Role updated successfully!',
        'dashboard.eventDeleted': 'Event deleted successfully',
        'dashboard.deleteFailed': 'Failed to delete event',
        'dashboard.greeting.morning': 'Good Morning',
        'dashboard.greeting.afternoon': 'Good Afternoon',
        'dashboard.greeting.evening': 'Good Evening',
        'dashboard.header.subtitle': 'Here\'s what\'s happening with your events today.',
        'dashboard.stats.totalEvents': 'Total Events',
        'dashboard.stats.eventsJoined': 'Events Joined',
        'dashboard.stats.eventsCreated': 'Events Created',
        'dashboard.stats.allTime': 'All Time',
        'dashboard.stats.active': 'Active',
        'dashboard.stats.publishedEvents': 'Published Events',
        'dashboard.stats.upcomingEvents': 'Upcoming Events',
        'dashboard.stats.thisMonth': 'This Month',
        'dashboard.stats.newActivity': 'New Activity',
        'dashboard.roleSwitcher.title': 'Dashboard View',
        'dashboard.roleSwitcher.subtitle': 'Switch between managing events and attending them',
        'dashboard.role.participant': 'Participant',
        'dashboard.role.organizer': 'Organizer',
        'dashboard.organizer.noEvents': 'No events yet',
        'dashboard.organizer.noEventsDesc': 'Start your journey by creating your first event. It only takes a few minutes!',
        'dashboard.participant.myRegistrations': 'My Registrations',
        'dashboard.participant.noRegistrations': 'No registrations yet',
        'dashboard.participant.noRegistrationsDesc': 'Explore our events and find something that interests you!',
        'dashboard.participant.browseEvents': 'Browse Events',
        'dashboard.eventCard.linkCopied': 'Event link copied',
        'dashboard.eventCard.registered': 'Registered:',
        'dashboard.status.confirmed': 'Confirmed',
        'dashboard.status.attended': 'Attended',
        'dashboard.status.cancelled': 'Cancelled',
        'dashboard.deleteModal.title': 'Delete Event?',
        'dashboard.deleteModal.confirm': 'Are you sure you want to delete',
        'dashboard.deleteModal.warning': 'This action cannot be undone.',
        'dashboard.deleteModal.deleteButton': 'Delete Event',
        'dashboard.deleteModal.deleting': 'Deleting...',

        // Calendar
        'calendar.title': 'Event Calendar',
        'calendar.subtitle': 'View all events in calendar view',
        'calendar.today': 'Today',
        'calendar.tomorrow': 'Tomorrow',
        'calendar.month': 'Month',
        'calendar.week': 'Week',
        'calendar.day': 'Day',
        'calendar.noEventsThisDay': 'No events on this day',
        'calendar.days.sun': 'Sun',
        'calendar.days.mon': 'Mon',
        'calendar.days.tue': 'Tue',
        'calendar.days.wed': 'Wed',
        'calendar.days.thu': 'Thu',
        'calendar.days.fri': 'Fri',
        'calendar.days.sat': 'Sat',

        // Profile
        'profile.title': 'Edit Profile',
        'profile.subtitle': 'Manage your profile information',
        'profile.fullName': 'Full Name',
        'profile.email': 'Email',
        'profile.phone': 'Phone Number',
        'profile.bio': 'Bio',
        'profile.photo': 'Profile Photo',
        'profile.uploadPhoto': 'Upload Photo',
        'profile.changePhoto': 'Change Photo',
        'profile.saving': 'Saving...',
        'profile.saveChanges': 'Save Changes',
        'profile.saved': 'Profile saved successfully!',

        // Auth
        'auth.login': 'Login',
        'auth.loginTitle': 'Login to Your Account',
        'auth.loginSubtitle': 'Welcome back!',
        'auth.loginWithGoogle': 'Login with Google',
        'auth.loggingIn': 'Logging in...',
        'auth.loginError': 'Login failed. Please try again.',
        'auth.register': 'Register',
        'auth.registerTitle': 'Create New Account',
        'auth.registerSubtitle': 'Join our community',
        'auth.email': 'Email',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Confirm Password',
        'auth.fullName': 'Full Name',
        'auth.createAccount': 'Create Account',
        'auth.alreadyHaveAccount': 'Already have an account?',
        'auth.dontHaveAccount': 'Don\'t have an account?',
        'auth.registerNow': 'Register now',
        'auth.orContinueWith': 'Or continue with',
        'auth.emailRequired': 'Email is required',
        'auth.passwordRequired': 'Password is required',
        'auth.passwordMinLength': 'Password must be at least 6 characters',
        'auth.passwordMismatch': 'Passwords do not match',
        'auth.nameRequired': 'Full name is required',
        'auth.registerSuccess': 'Registration successful! Please check your email for verification.',
        'auth.registerError': 'Registration failed. Please try again.',
        'auth.invalidCredentials': 'Invalid email or password',
        'auth.emailAlreadyExists': 'Email already exists',
        'auth.emailVerified': 'Email verified successfully. Please login.',
        'auth.invalidEmail': 'Invalid email',
        'auth.humanVerificationRequired': 'Human verification required',
        'auth.verificationFailed': 'Verification failed',
        'auth.humanVerificationFailed': 'Human verification failed',
        'auth.loginSuccess': 'Login successful!',
        'auth.verificationRequired': 'Verification required to proceed.',
        'auth.redirectingGoogle': 'Redirecting to Google...',
        'auth.agreeToTerms': 'By logging in, you agree to',
        'auth.agreeToTermsRegister': 'By registering, you agree to',
        'auth.termsAndConditions': 'Terms & Conditions',
        'auth.passwordMinLength8': 'Password must be at least 8 characters',
        'auth.passwordMustContainNumber': 'Password must contain a number',
        'auth.passwordMustContainNumberHint': 'Contains a number (0-9)',
        'auth.registering': 'Registering...',

        // Create/Edit Event
        'eventForm.createTitle': 'Create New Event',
        'eventForm.editTitle': 'Edit Event',
        'eventForm.basicInfo': 'Basic Information',
        'eventForm.eventTitle': 'Event Title',
        'eventForm.description': 'Description',
        'eventForm.category': 'Category',
        'eventForm.selectCategory': 'Select Category',
        'eventForm.dateTime': 'Date & Time',
        'eventForm.startDate': 'Start Date',
        'eventForm.endDate': 'End Date',
        'eventForm.locationInfo': 'Location Information',
        'eventForm.location': 'Location',
        'eventForm.registrationInfo': 'Registration Information',
        'eventForm.registrationFee': 'Registration Fee',
        'eventForm.maxParticipants': 'Max Participants',
        'eventForm.unlimited': 'Unlimited',
        'eventForm.imageUpload': 'Upload Image',
        'eventForm.uploadImage': 'Upload Event Image',
        'eventForm.changeImage': 'Change Image',
        'eventForm.speakers': 'Speakers',
        'eventForm.addSpeaker': 'Add Speaker',
        'eventForm.speakerName': 'Speaker Name',
        'eventForm.speakerTitle': 'Title',
        'eventForm.speakerBio': 'Speaker Bio',
        'eventForm.speakerPhoto': 'Speaker Photo',
        'eventForm.removeSpeaker': 'Remove Speaker',
        'eventForm.customFields': 'Custom Registration Form',
        'eventForm.addField': 'Add Field',
        'eventForm.fieldLabel': 'Field Label',
        'eventForm.fieldType': 'Field Type',
        'eventForm.required': 'Required',
        'eventForm.status': 'Status',
        'eventForm.draft': 'Draft',
        'eventForm.published': 'Published',
        'eventForm.creating': 'Creating Event...',
        'eventForm.updating': 'Updating Event...',
        'eventForm.create': 'Create Event',
        'eventForm.update': 'Update Event',
        'eventForm.created': 'Event created successfully!',
        'eventForm.updated': 'Event updated successfully!',
        'eventForm.createSubtitle': 'Share your event with the world. Fill in the details below to get started.',
        'eventForm.editSubtitle': 'Update your event information.',
        'eventForm.tabBasic': 'Basic Info',
        'eventForm.tabSpeakers': 'Speakers',
        'eventForm.tabRegistration': 'Registration Form',
        'eventForm.tabImages': 'Custom Image Form',
        'eventForm.eventDetails': 'Event Details',
        'eventForm.eventDetailsDesc': 'Basic information about your event.',
        'eventForm.coverImage': 'Event Cover Image',
        'eventForm.imageRatioWarning': 'Recommended image ratio 4:5. Images will be cropped if ratio does not match.',
        'eventForm.clickUpload': 'Click to upload or drag and drop',
        'eventForm.imageFormat': 'PNG, JPG or WEBP (MAX. 5MB)',
        'eventForm.titlePlaceholder': 'e.g., Annual Tech Conference 2024',
        'eventForm.descriptionPlaceholder': 'Describe your event using markdown...',
        'eventForm.markdownSupport': 'Supports Markdown formatting',
        'eventForm.startDateTime': 'Start Date & Time',
        'eventForm.endDateTime': 'End Date & Time',
        'eventForm.locationPlaceholder': 'e.g., Zoom Meeting or Physical Address',
        'eventForm.selectCategoryPlaceholder': 'Select category...',
        'eventForm.capacityPlaceholder': 'Maximum participants',
        'eventForm.registrationFeeIDR': 'Registration Fee (IDR)',
        'eventForm.feePlaceholder': '0 (Free event)',
        'eventForm.feeHelper': 'Leave as 0 for free events. If you set a fee, make sure to add a payment proof upload field below.',
        'eventForm.draftDesc': 'Save for later, not visible to public',
        'eventForm.publishedDesc': 'Visible to everyone immediately',
        'eventForm.registrationFormTitle': 'Registration Form',
        'eventForm.registrationFormDesc': 'Customize what information you need from attendees.',
        'eventForm.noCustomFields': 'No Custom Fields',
        'eventForm.noCustomFieldsDesc': 'Start by adding fields to collect specific information from your attendees.',
        'eventForm.addFirstField': 'Add your first field',
        'eventForm.fieldName': 'Field Name',
        'eventForm.fieldNamePlaceholder': 'e.g., Phone Number',
        'eventForm.type': 'Type',
        'eventForm.typeText': 'Text',
        'eventForm.typeEmail': 'Email',
        'eventForm.typeNumber': 'Number',
        'eventForm.typeTextarea': 'Textarea',
        'eventForm.typeSelect': 'Select',
        'eventForm.typeFile': 'File Upload',
        'eventForm.speakersTitle': 'Speakers',
        'eventForm.speakersDesc': 'Who will be presenting at your event?',
        'eventForm.noSpeakers': 'No Speakers Added',
        'eventForm.noSpeakersDesc': 'Highlight the experts and guests who will be attending.',
        'eventForm.addFirstSpeaker': 'Add your first speaker',
        'eventForm.speakerNumber': 'Speaker',
        'eventForm.customImagesTitle': 'Custom Images for Registration Form',
        'eventForm.customImagesDesc': 'Add custom images to be displayed in the registration form.',
        'eventForm.addImage': 'Add Image',
        'eventForm.noCustomImages': 'No Custom Images',
        'eventForm.noCustomImagesDesc': 'Add images to enrich your registration form.',
        'eventForm.addFirstImage': 'Add your first image',
        'eventForm.imageTitle': 'Image Title',
        'eventForm.imageDescription': 'Image Description',
        'eventForm.uploadingImage': 'Compressing and uploading image...',
        'eventForm.imageUploaded': 'Image uploaded successfully!',
        'eventForm.imageUploadFailed': 'Failed to upload image',
        'eventForm.pleaseLogin': 'Please login first',
        'eventForm.loginError': 'An error occurred during login verification',
        'eventForm.fillRequired': 'Please fill in all required fields',
        'eventForm.createError': 'Failed to create event',
        'eventForm.updateError': 'Failed to update event',
        'eventForm.paymentProofAdded': 'Payment proof upload form added automatically',

        // Registrations
        'registrations.title': 'Event Registrations',
        'registrations.subtitle': 'Manage registered participants',
        'registrations.total': 'Total Registrations',
        'registrations.export': 'Export Data',
        'registrations.name': 'Name',
        'registrations.email': 'Email',
        'registrations.phone': 'Phone',
        'registrations.registeredAt': 'Registration Date',
        'registrations.status': 'Status',
        'registrations.approved': 'Approved',
        'registrations.pending': 'Pending',
        'registrations.rejected': 'Rejected',
        'registrations.noRegistrations': 'No registrations yet',

        // About
        'about.title': 'About Ngevent',
        'about.appTitle': 'About Ngevent App',
        'about.appDesc': 'Ngevent helps you create and manage online events easily. Create events, manage participants, and view basic event information through a simple dashboard.',
        'about.featuresTitle': 'Key Features',
        'about.featuresDesc': 'Some key features of Ngevent:',
        'about.feature1': 'Create and manage online events',
        'about.feature2': 'Participant registration',
        'about.feature3': 'Simple dashboard to view event data',
        'about.feature4': 'Responsive interface for mobile devices',
        'about.feature5': 'Multi-language support',
        'about.devTitle': 'Developer Information',
        'about.devDesc': 'Ngevent is created and maintained by the DevOps Jogja community. This project uses modern technologies such as Next.js, TypeScript, Tailwind CSS, and Supabase.',
        'about.community': 'Community:',
        'about.tech': 'Technology:',
        'about.supportTitle': 'Support and Contact',
        'about.supportDesc': 'We maintain the service and security of the platform. If you need assistance, please contact the DevOps Jogja community.',
        'about.support1': 'Routine monitoring and maintenance',
        'about.support2': 'Regular backups and security updates',
        'about.support3': 'Technical support from the community',
        'about.contact': 'Contact:',
        'about.telegram': 'Telegram:',

        // Terms
        'terms.title': 'Terms and Conditions',
        'terms.lastUpdated': 'Last updated:',
        'terms.section1.title': '1. Acceptance of Terms',
        'terms.section1.content': 'By accessing and using the Ngevent platform, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our platform.',
        'terms.section2.title': '2. Service Description',
        'terms.section2.content': 'Ngevent is an online event management platform that facilitates organizers and participants in managing and participating in various events. Our services include event creation, participant registration, payment management, and event-related communication.',
        'terms.section3.title': '3. User Accounts',
        'terms.section3.content': 'To use our services, you must create an account by providing accurate and complete information. You are responsible for:',
        'terms.section3.list1': 'Maintaining the confidentiality of your password',
        'terms.section3.list2': 'Using your account only for lawful purposes',
        'terms.section3.list3': 'Providing correct and up-to-date information',
        'terms.section3.list4': 'Reporting suspicious activity on your account',
        'terms.section4.title': '4. Prohibited Use',
        'terms.section4.content': 'You are prohibited from using our platform to:',
        'terms.section4.list1': 'Violate applicable laws or regulations',
        'terms.section4.list2': 'Send inappropriate, insulting, or illegal content',
        'terms.section4.list3': 'Disrupt the operation of our platform or servers',
        'terms.section4.list4': 'Attempt to access unauthorized areas',
        'terms.section4.list5': 'Copy or distribute content without permission',
        'terms.section5.title': '5. User Content',
        'terms.section5.content': 'You are responsible for the content you upload or share on our platform. We reserve the right to remove content that violates these terms and conditions without prior notice.',
        'terms.section6.title': '6. Payment and Refunds',
        'terms.section6.content': 'For paid events:',
        'terms.section6.list1': 'Payment is made through available payment gateways',
        'terms.section6.list2': 'Refunds are only made according to the event organizer\'s policy',
        'terms.section6.list3': 'We are not responsible for payment disputes with organizers',
        'terms.section7.title': '7. Privacy',
        'terms.section7.content': 'We respect your privacy. Personal information collected is used only for service purposes and in accordance with our Privacy Policy.',
        'terms.section8.title': '8. Disclaimer of Warranties',
        'terms.section8.content': 'Our platform is provided "as is" without any warranties. We are not liable for any damages arising from the use of this platform.',
        'terms.section9.title': '9. Limitation of Liability',
        'terms.section9.content': 'We are not liable for any direct, indirect, incidental, or consequential damages arising from the use of our platform.',
        'terms.section10.title': '10. Changes to Terms',
        'terms.section10.content': 'We reserve the right to change these terms and conditions at any time. Changes will be notified through our platform.',
        'terms.section11.title': '11. Governing Law',
        'terms.section11.content': 'These terms and conditions are governed by the laws of the Republic of Indonesia.',
        'terms.section12.title': '12. Contact Us',
        'terms.section12.content': 'If you have any questions about these terms and conditions, please contact us via email or the support feature on the platform.',
        'terms.backToLogin': 'Back to Login',
        'terms.backToRegister': 'Back to Register',
    },
};
